### PR TITLE
Left Column - Full Height + templates cleanup

### LINKED ISSUE #332: Left Column - Full Height?
## what
* Make column full-height below the header (e.g. to the bottom of the page)

Is it possible to extend the left column to the bottom of the page?

image

### PR DESCRIPTION
**Pull request by finnsky**
## what
* Added full height to left sidebar. 
* Reworked templates. They were unreadable. 

## why
* closes #332

### CODE REVIEW

**Comment by finnsky** [comment]
[Image from Gyazo](https://gyazo.com/a1d3c78d919cf5b3c49fe62ef165e11b)

**Comment by osterman** [comment]
Something feels wrong...
image

**Comment by osterman** [comment]
image

**Comment by osterman** [comment]
My fault. I had disabled yarn. Looks good.

**Pull request merged**
