### PR TITLE
Code Block Modals

### PR DESCRIPTION
**Pull request by finnsky**
## what
* Changed code display to featherlight popup.

## why
* #97

### CODE REVIEW

**Comment by osterman** [comment]
Can you add screenshot? Thx!

**Comment by finnsky** [comment]
[Image from Gyazo](https://gyazo.com/0df9cb17524f2f22ad89ea065dc53c25)

**Comment by finnsky** [comment]
but issues with small parts of code 
[Image from Gyazo](https://gyazo.com/36d648be905a6d6c77a0cdf2f39c2aea)

**Comment by finnsky** [comment]
and with very big
[Image from Gyazo](https://gyazo.com/3b4b3263c9562bb98c539163631f21e5)

**Comment by osterman** [comment]
Do you know what causes the issue with the small codeblocks?

If yiou want, you can hide the button when text < N bytes

**Comment by finnsky** [comment]
1. enabled common dialog component for code-blocks. added same margins/paddings for all code parts.
2. added checking if block.height > 250 then expand added. 
[Image from Gyazo](https://gyazo.com/0adede4ff84935637a718d7e47e8eecb)

**Comment by osterman** [comment]
I think it looks much better.

**Pull request merged**
