### PR TITLE
Added Chapter Links to Chapter Titles #80

### PR DESCRIPTION
**Pull request by finnsky**
## what
* Changed js logic to detect page content headings.

## why
* It has wrong selector.

### CODE REVIEW

**Comment by finnsky** [comment]
#80

**Comment by osterman** [comment]
@finnsky please add inline screenshots. Makes CR easier.

**Comment by finnsky** [comment]
hover

hover behaviour works for h2-h6. not for h1. what seems right from SEO side, page should have one h1
```
h2:hover .anchor, h3:hover .anchor, h4:hover .anchor, h5:hover .anchor, h6:hover .anchor {
  visibility: visible;
}
```

**Comment by osterman** [comment]
We should hard fork the JS rather than update the upstream version.

image

**Pull request merged**
