### PR TITLE
Fixed Text Wrapping on Homepage

### LINKED ISSUE #170: Fix Text Wrapping on Homepage
## what
* Fix text wrapping

image

## why
* Looks ugly

### PR DESCRIPTION
**Pull request by finnsky**
## what
* Reworked landing top. Added missed font family. 

## why
* Landing should looks cool.

closes #170

### CODE REVIEW

**Comment by finnsky** [comment]
mobile https://gyazo.com/7ad7133b44c082024f2d0e9397dc7878
desktop https://gyazo.com/7aa096a7b9197a96227f7c93613c6688

**Comment by osterman** [comment]
Looks great! A few requests.

- [ ] Use the original case-sensitive font for homepage header (not uppercase). 
- [ ] Reduce button size on desktop (mobile ok)

**Comment by finnsky** [comment]
desktop
mobile

### also

* added svg for cloud image
* added svg for logo

**Comment by osterman** [comment]
The new cloud feels overwhelmingly large. It doesn't have to be as small as it is today, but maybe play with the size a little?

Here's today:

image

**Comment by osterman** [comment]
@finnsky did you see the comments regarding size of cloud?

**Comment by finnsky** [comment]
hi! reworked header. seems me better to align all. for 1024+ screens

**Comment by osterman** [comment]
I prefer we stick with the standard banner header that's roughly 1/3 height of the screen. There's too much unnecessary white space in this version for my liking. .

**Pull request merged**
