### PR TITLE
Switch from CSS to structured SASS.

### PR DESCRIPTION
**Pull request by finnsky**
## what
* moved custom css to SASS. Components more or less structured. Moved components tested for regressions. Some components still left in custom.scss file. We need to move them to their components.
* added gulpfile for tasks management. Currently it needs nodejs. But usage of simple css for quickfixes still possible. in custom.css file. We need to think easy way to use sass for everyone. Docker with nodejs maybe? [we may take some ideas here](https://github.com/netlify/victor-hugo)
* added autoprefixer. also would be cool to add linter. For sass and resulted css. 
* i saw that main fonts are proxima and open sans but they are not enabled
maybe we need to add <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700&amp;subset=latin-ext" rel="stylesheet"> in header?
* enabled source maps but i'm sure we need to disable it. via env variables.
* managed header with BEM classes. 

## why
* Current CSS is chaos. And it needs some structure to manage frontend without regressions. Also i think that "hugo-theme-docdock" needs to be managed with what components way since it will not updated from its repo. One more improvement may became webpack.

### CODE REVIEW

**Comment by osterman** [comment]
Since this requires adding a new dependency on `node`, I think we'll first want to dockerize this build process for CI/CD.  We'll do that as a separate PR, so as to reduce scope on this one. Also, I think I want to do that before we consider merging this due to build complications.

**Comment by finnsky** [comment]
Cool. Thanks for review. I think we can add extra css file for next work, to avoid lot of conflicts with this PR until build will dockerized.

**Comment by osterman** [comment]
@goruha don't want to merge until we dockerize. @alebabai will work on dockerization this week.

**Comment by osterman** [comment]
https://github.com/cloudposse/docs/pull/137

**Pull request merged**
