### PR TITLE
Implement GitHub Style Tags

### LINKED ISSUE #306: Implement GitHub Style Tags
## what
* Use GitHub design for tags

image

## references
* https://github.com/cloudposse/geodesic

## why
* This looks cleaner than our current strategy for displaying tags

### PR DESCRIPTION
**Pull request by finnsky**
## what
* Added styles for tags.

## why
* closes #306

### CODE REVIEW

**Comment by finnsky** [comment]
[Image from Gyazo](https://gyazo.com/b61ae579b3481bd5754adf2f41399efd)

**Comment by osterman** [comment]
Actually, please implement tags like in the mockup. I really like that. 

Regarding colors: I want to change things up a little bit. That said I don't have a pallet in mind. Overall, want to borrow more of the GitHub color scheme, but maintain our dark grey color.

Also see:  https://github.com/cloudposse/docs/issues/281

**Comment by osterman** [comment]
To be clear, please make it look like this:

image

Not like this:
image


## todo
- [ ] move tags below description at the top
- [ ] remove `#` hash symbol
- [ ] set top/bottom margin respectively
- [ ] ensure font-sizes is roughly the same as on github
- [ ] ensure spacing between tags roughly the same as on github
- [ ] ensure line height roughly the same as on github (slightly narrower I think than what it is now)

**Comment by finnsky** [comment]
[Image from Gyazo](https://gyazo.com/12da41bb2a726666fa9a70179436fdfa)

**Pull request merged**
