### PR TITLE
Search results page

### PR DESCRIPTION
**Pull request by finnsky**
## what
* Added search page with pagination and 'results per page' selectbox.
* Added bootstrap to global styles. To theme small UI elements.

### CODE REVIEW

**Comment by finnsky** [comment]
[Image from Gyazo](https://gyazo.com/969e2332d97b406400b35205f4f1f06e)

**Comment by osterman** [comment]
Can we float this to the right?
image

**Comment by osterman** [comment]
Let's format the results like this
image

**Comment by finnsky** [comment]
[Image from Gyazo](https://gyazo.com/1179e45c2848ead0fc39128925192e52)

**Comment by osterman** [comment]
We should get rid of this: 
image

**Comment by osterman** [comment]
Let's get rid of this button this page too:

image

**Comment by osterman** [comment]
Let's move tags after category to reduce the amount of white space which feels excessive. 
image

**Comment by osterman** [comment]
image
Search on both lines feels redundant. On the second line, let's remove the word "Search" and begin with "Results for"

**Comment by osterman** [comment]
@finnsky rebase needed

**Pull request merged**
